
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybt2c2p2b3F1p6tdiC8PyIrUOwoaQKpQ',
    appId: '1:881112476381:web:b3f39524b4f3db5877c934',
    messagingSenderId: '881112476381',
    projectId: 'zoidberg-app',
    authDomain: 'zoidberg-app.firebaseapp.com',
    storageBucket: 'zoidberg-app.firebasestorage.app',
    measurementId: 'G-J2W70LZM1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkiA8agiib6ml4hDkX6chfTidOeHlvf3A',
    appId: '1:881112476381:android:7911593daf1880de77c934',
    messagingSenderId: '881112476381',
    projectId: 'zoidberg-app',
    storageBucket: 'zoidberg-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPSS0ICPMlfwyYvUywTXV7Bmk85W9dxHU',
    appId: '1:881112476381:ios:00c43495bf8ecd5577c934',
    messagingSenderId: '881112476381',
    projectId: 'zoidberg-app',
    storageBucket: 'zoidberg-app.firebasestorage.app',
    iosBundleId: 'com.example.zoidberg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPSS0ICPMlfwyYvUywTXV7Bmk85W9dxHU',
    appId: '1:881112476381:ios:00c43495bf8ecd5577c934',
    messagingSenderId: '881112476381',
    projectId: 'zoidberg-app',
    storageBucket: 'zoidberg-app.firebasestorage.app',
    iosBundleId: 'com.example.zoidberg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBybt2c2p2b3F1p6tdiC8PyIrUOwoaQKpQ',
    appId: '1:881112476381:web:8a789cc961fa336077c934',
    messagingSenderId: '881112476381',
    projectId: 'zoidberg-app',
    authDomain: 'zoidberg-app.firebaseapp.com',
    storageBucket: 'zoidberg-app.firebasestorage.app',
    measurementId: 'G-RF80CPS16V',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBPSS0ICPMlfwyYvUywTXV7Bmk85W9dxHU',
    appId: '1:881112476381:ios:00c43495bf8ecd5577c934',
    messagingSenderId: '881112476381',
    projectId: 'zoidberg-app',
    authDomain: 'zoidberg-app.firebaseapp.com',
    storageBucket: 'zoidberg-app.firebasestorage.app',
    // Asegúrate de incluir todas las claves que te proporcione Firebase
  );

}